export default 
        [{"Term":"baseline","Definition":null},
        {"Term":"bias","Definition":null},
        {"Term":"cluster sampling","Definition":null},
        {"Term":"community built sampling frames","Definition":null},
        {"Term":"design effect","Definition":null},
        {"Term":"end-line","Definition":null},
        {"Term":"estimation","Definition":"This is just a placeholder definition for estimation. More content will be added later."},
        {"Term":"idp","Definition":null},
        {"Term":"indicator","Definition":null},
        {"Term":"intra cluster correlation","Definition":null},
        {"Term":"key informants","Definition":null},
        {"Term":"margin of error","Definition":null},
        {"Term":"migrant","Definition":null},
        {"Term":"multi-stage sampling","Definition":null},
        {"Term":"precision of an estimate","Definition":null},
        {"Term":"refugee","Definition":null},
        {"Term":"sampling frame","Definition":null},
        {"Term":"sampling unit","Definition":null},
        {"Term":"selection with probability proportional to size","Definition":null},
        {"Term":"simple random sampling","Definition":null},
        {"Term":"snowball sampling","Definition":null},
        {"Term":"statistical inferences","Definition":null},
        {"Term":"stratification","Definition":null},
        {"Term":"study population","Definition":null},
        {"Term":"systematic sampling","Definition":null},
        {"Term":"target population","Definition":null},
        {"Term":"type of error in data","Definition":null}]
