export default 
[{"Term":"baseline","Definition":"","slug":"baseline"},
{"Term":"bias","Definition":"","slug":"bias"},
{"Term":"cluster sampling","Definition":"","slug":"cluster-sampling"},
{"Term":"community built sampling frames","Definition":"","slug":"community-built-sampling-frames"},
{"Term":"design effect","Definition":"","slug":"design-effect"},
{"Term":"end-line","Definition":"","slug":"end-line"},
{"Term":"Estimation","Definition":"","slug":"estimation"},
{"Term":"idp","Definition":"","slug":"idp"},
{"Term":"indicator","Definition":"","slug":"indicator"},
{"Term":"intra cluster correlation","Definition":"","slug":"intra-cluster-correlation"},
{"Term":"key informants","Definition":"","slug":"key-informants"},
{"Term":"margin of error","Definition":"","slug":"margin-of-error"},
{"Term":"migrant","Definition":"","slug":"migrant"},
{"Term":"multi-stage sampling","Definition":"","slug":"multi-stage-sampling"},
{"Term":"precision of an estimate","Definition":"","slug":"precision-of-an-estimate"},
{"Term":"refugee","Definition":"","slug":"refugee"},
{"Term":"sampling frame","Definition":"","slug":"sampling-frame"},
{"Term":"sampling unit","Definition":"","slug":"sampling-unit"},
{"Term":"selection with probability proportional to size","Definition":"","slug":"selection-with-probability-proportional-to-size"},
{"Term":"simple random sampling","Definition":"","slug":"simple-random-sampling"},
{"Term":"snowball sampling","Definition":"","slug":"snowball-sampling"},
{"Term":"statistical inferences","Definition":"","slug":"statistical-inferences"},
{"Term":"stratification","Definition":"","slug":"stratification"},
{"Term":"study population","Definition":"","slug":"study-population"},
{"Term":"systematic sampling","Definition":"","slug":"systematic-sampling"},
{"Term":"target population","Definition":"","slug":"target-population"},
{"Term":"type of error in data","Definition":"","slug":"type-of-error-in-data"},
{"Term":"Respondent-Driven Sampling","Definition":"<p>Respondent-driven sampling (RDS), combines ","slug":"Respondent-Driven-Sampling"},
{"Term":"Non-probability-based sampling","Definition":"<p>Is any sampling method based where some elements of the population have no chance of selection because the sampling strategy is based on decisions related to convenience, quotas or deliberate choice of elements of the population. In these cases, the probability of selection can't be determined. Because the selection of elements is non-random, non-probability-based sampling does not allow the estimation of sampling errors, and it is not possible to assume that biases cancel each other out. The ability of making inferences about the population is limited when using non-probability based sampling and the information generated needs to be treated carefully.<br />Some adaptations of non-probability-based sampling have been made to allow for limited inferences. An example of this is <a href='#'>Respondent-Driven Sampling</a>, (RDS);, that proposes ways of estimating weights to try to account for biases in when using snowball sampling.</p>","slug":"Non-probability-based-sampling"},
{"Term":"Probability-based sampling","Definition":"<p>Is a process to select a sample in which every unit in the population has a chance (greater than zero) of being selected in the sample, and this probability can be accurately determined. The fact that the probability can be established does not mean that it is always calculated. cThis makes it possible to produce unbiased estimates of population totals, by weighting sampled units according to their probability of selection.</p>","slug":"Probability-based-sampling"}]
