export default [
        "Baseline",
        "Bias",
        "Cluster sampling",
        "Design effect",
        "End-line",
        "Estimate",
        "Indicator",
        "Intra cluster correlation",
        "Margin of error",
        "Multi-stage sampling",
        "Precision of an estimate",
        "Sampling frame",
        "Sampling unit",
        "Selection with probability proportional to size",
        "Simple random sampling",
        "Statistical inferences",
        "Stratification",
        "Study population",
        "Systematic sampling",
        "Target population",
        "Snowball sampling",
        "community built sampling frames",
        "Key informants",
        "systematic sampling",
        "type of error in data",
        "Refugee",
        "IDP",
        "migrant"
]